### ISSUE TITLE
Local cover files ignored if path has square brackets

### ISSUE THREAD

**Issue by de666** [mopidy/mopidy-local-images#21]
If the folder name (dirname) contains square brackets, the plugin fails to fetch the album art files inside of that folder.
It is due to this behaviour [https://stackoverflow.com/questions/2595119/python-glob-and-bracket-characters](https://stackoverflow.com/questions/2595119/python-glob-and-bracket-characters)
To make it works it is enough to make change line 182 of library.py to this one
`dirname = os.path.dirname(path).decode('utf-8').replace('[', '[[]')`

**Comment by tkem** [comment]
The link provided is (no longer?) valid...

**Comment by de666** [comment]
Link updated

**Comment by tkem** [comment]
Thanks!

**Comment by tkem** [comment]
Why the `decode('utf-8')`?

**Comment by de666** [comment]
to handle folder names with characters other than ASCII

**Comment by tkem** [comment]
Should be fixed in new Mopidy-Local extension for Mopidy v3.0.0.
