### ISSUE TITLE
Make symlinks instead of copying cover files

### ISSUE THREAD

**Issue by de666** [mopidy/mopidy-local-images#22]
When an external cover file is available, if possible (not on windows), the plugin should make a symlink instead of copying the file to save disk space and avoid files duplication.
#25

**Comment by tkem** [comment]
@de666: Frankly, I'm not sure if this is worth the effort (at least from an implementation point of view). If you feel strongly about this, please consider opening a new issue for this in the new Mopidy-Local repository, which will replace Mopidy-Local-Images for Mopidy v3.
